export enum PermissionStatus {
  CHECKING = "CHECKING",
  GRANTED = "GRANTED",
  DENIED = "DENIED",
  BLOQUED = "BLOQUED",
  LIMITED = "LIMITED",
  UNAVAILABLE = "UNAVAILABLE",
  UNDETERMINED = "UNDETERMINED",
}
